Repository DEV-MUGLES/pickk-admin, pull requests merged in 2020-01, with the labels that each got.

#6 [구현] LoginPage UI 구현
  pages/login.tsx
  src/components/organisms/GFooter.tsx
  src/components/organisms/LoginFooter.tsx
  src/components/organisms/LoginForm.tsx
  src/components/templates/MainLayout.tsx
Labels: implement

#11 [feature] add BoardFilterHeader
  pages/login.tsx
  src/components/atoms/logo/admin.tsx
  src/components/organisms/Board/Filter/Header.tsx
  src/components/organisms/LoginForm.tsx
Labels: implement

#13 [Feature] Add boardFilterButtonArea
  src/components/organisms/Board/Filter/ButtonArea.tsx
Labels: in progress

#12 [Feature] Add BoardFilterRow
  src/components/atoms/colors/index.ts
  src/components/molecules/BoardFilter/BodyRow.tsx
  src/components/organisms/Board/Filter/Body.tsx
  src/components/templates/MainLayout.tsx
Labels: implement, in progress

#17 [Feature] Add BoardFilter
  src/components/molecules/BoardFilter/BodyRow.tsx
  src/components/organisms/Board/Filter/Body.tsx
  src/components/organisms/Board/Filter/ButtonArea.tsx
  src/components/organisms/Board/Filter/Header.tsx
  src/components/organisms/Board/Filter/index.tsx
  src/components/templates/Board.tsx
  src/contexts/BoardFilter.tsx
Labels: implement

#15 [Feature] Add Board Filter Input Components
  package.json
  pages/dashboard.tsx
  pages/products/index.tsx
  src/components/atoms/space/index.tsx
  src/components/molecules/BoardFilter/BodyRow.tsx
  src/components/molecules/BoardFilter/input/DatePicker.tsx
  src/components/molecules/BoardFilter/input/InputBox.tsx
  src/components/molecules/BoardFilter/input/ItemCategorySelector.tsx
  src/components/molecules/BoardFilter/input/MultiChecker.tsx
  src/components/molecules/BoardFilter/input/SelectInput.tsx
  src/components/molecules/BoardFilter/input/Selector.tsx
  src/contexts/BoardFilter.tsx
  src/models/ItemCategory.ts
Labels: implement, in progress

#19 [Feature] add dashboard-card-header
  src/components/molecules/button/CardReload.tsx
  src/components/organisms/Dashboard/Card/Header.tsx
  src/lib/DateParser.ts
Labels: in progress

#21 [Feature] Add DashboardCardBody
  src/components/molecules/button/CardReload.tsx
  src/components/organisms/Dashboard/Card/Body.tsx
  src/components/organisms/Dashboard/Card/Header.tsx
Labels: implement, in progress
